// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: v1/controlplane.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_LookupCredentials_FullMethodName = "/vbuckets.v1.ControlPlane/LookupCredentials"
	ControlPlane_LookupBaseHost_FullMethodName    = "/vbuckets.v1.ControlPlane/LookupBaseHost"
	ControlPlane_LookupVBucket_FullMethodName     = "/vbuckets.v1.ControlPlane/LookupVBucket"
	ControlPlane_CreateVBucket_FullMethodName     = "/vbuckets.v1.ControlPlane/CreateVBucket"
	ControlPlane_ListVBuckets_FullMethodName      = "/vbuckets.v1.ControlPlane/ListVBuckets"
	ControlPlane_ListenForDeltas_FullMethodName   = "/vbuckets.v1.ControlPlane/ListenForDeltas"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlPlane is the service that users implement on their control plane
// server. The vbuckets proxy connects to this service to resolve virtual
// credentials and bucket mappings.
type ControlPlaneClient interface {
	LookupCredentials(ctx context.Context, in *LookupCredentialsRequest, opts ...grpc.CallOption) (*LookupCredentialsResponse, error)
	LookupBaseHost(ctx context.Context, in *LookupBaseHostRequest, opts ...grpc.CallOption) (*LookupBaseHostResponse, error)
	LookupVBucket(ctx context.Context, in *LookupVBucketRequest, opts ...grpc.CallOption) (*LookupVBucketResponse, error)
	CreateVBucket(ctx context.Context, in *CreateVBucketRequest, opts ...grpc.CallOption) (*CreateVBucketResponse, error)
	ListVBuckets(ctx context.Context, in *ListVBucketsRequest, opts ...grpc.CallOption) (*ListVBucketsResponse, error)
	// ListenForDeltas opens a server-streaming RPC that pushes cache updates
	// to the proxy. The control plane sends deltas whenever credentials, base
	// hosts, or vbucket mappings change, allowing the proxy to maintain
	// long-lived caches with fast invalidation.
	ListenForDeltas(ctx context.Context, in *ListenForDeltasRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Delta], error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) LookupCredentials(ctx context.Context, in *LookupCredentialsRequest, opts ...grpc.CallOption) (*LookupCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupCredentialsResponse)
	err := c.cc.Invoke(ctx, ControlPlane_LookupCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) LookupBaseHost(ctx context.Context, in *LookupBaseHostRequest, opts ...grpc.CallOption) (*LookupBaseHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupBaseHostResponse)
	err := c.cc.Invoke(ctx, ControlPlane_LookupBaseHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) LookupVBucket(ctx context.Context, in *LookupVBucketRequest, opts ...grpc.CallOption) (*LookupVBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupVBucketResponse)
	err := c.cc.Invoke(ctx, ControlPlane_LookupVBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) CreateVBucket(ctx context.Context, in *CreateVBucketRequest, opts ...grpc.CallOption) (*CreateVBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVBucketResponse)
	err := c.cc.Invoke(ctx, ControlPlane_CreateVBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListVBuckets(ctx context.Context, in *ListVBucketsRequest, opts ...grpc.CallOption) (*ListVBucketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVBucketsResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ListVBuckets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListenForDeltas(ctx context.Context, in *ListenForDeltasRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Delta], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[0], ControlPlane_ListenForDeltas_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListenForDeltasRequest, Delta]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_ListenForDeltasClient = grpc.ServerStreamingClient[Delta]

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
//
// ControlPlane is the service that users implement on their control plane
// server. The vbuckets proxy connects to this service to resolve virtual
// credentials and bucket mappings.
type ControlPlaneServer interface {
	LookupCredentials(context.Context, *LookupCredentialsRequest) (*LookupCredentialsResponse, error)
	LookupBaseHost(context.Context, *LookupBaseHostRequest) (*LookupBaseHostResponse, error)
	LookupVBucket(context.Context, *LookupVBucketRequest) (*LookupVBucketResponse, error)
	CreateVBucket(context.Context, *CreateVBucketRequest) (*CreateVBucketResponse, error)
	ListVBuckets(context.Context, *ListVBucketsRequest) (*ListVBucketsResponse, error)
	// ListenForDeltas opens a server-streaming RPC that pushes cache updates
	// to the proxy. The control plane sends deltas whenever credentials, base
	// hosts, or vbucket mappings change, allowing the proxy to maintain
	// long-lived caches with fast invalidation.
	ListenForDeltas(*ListenForDeltasRequest, grpc.ServerStreamingServer[Delta]) error
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) LookupCredentials(context.Context, *LookupCredentialsRequest) (*LookupCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupCredentials not implemented")
}
func (UnimplementedControlPlaneServer) LookupBaseHost(context.Context, *LookupBaseHostRequest) (*LookupBaseHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupBaseHost not implemented")
}
func (UnimplementedControlPlaneServer) LookupVBucket(context.Context, *LookupVBucketRequest) (*LookupVBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupVBucket not implemented")
}
func (UnimplementedControlPlaneServer) CreateVBucket(context.Context, *CreateVBucketRequest) (*CreateVBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVBucket not implemented")
}
func (UnimplementedControlPlaneServer) ListVBuckets(context.Context, *ListVBucketsRequest) (*ListVBucketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVBuckets not implemented")
}
func (UnimplementedControlPlaneServer) ListenForDeltas(*ListenForDeltasRequest, grpc.ServerStreamingServer[Delta]) error {
	return status.Error(codes.Unimplemented, "method ListenForDeltas not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_LookupCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).LookupCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_LookupCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).LookupCredentials(ctx, req.(*LookupCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_LookupBaseHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupBaseHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).LookupBaseHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_LookupBaseHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).LookupBaseHost(ctx, req.(*LookupBaseHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_LookupVBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupVBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).LookupVBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_LookupVBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).LookupVBucket(ctx, req.(*LookupVBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_CreateVBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).CreateVBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_CreateVBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).CreateVBucket(ctx, req.(*CreateVBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListVBuckets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVBucketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListVBuckets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListVBuckets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListVBuckets(ctx, req.(*ListVBucketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListenForDeltas_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenForDeltasRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServer).ListenForDeltas(m, &grpc.GenericServerStream[ListenForDeltasRequest, Delta]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_ListenForDeltasServer = grpc.ServerStreamingServer[Delta]

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vbuckets.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LookupCredentials",
			Handler:    _ControlPlane_LookupCredentials_Handler,
		},
		{
			MethodName: "LookupBaseHost",
			Handler:    _ControlPlane_LookupBaseHost_Handler,
		},
		{
			MethodName: "LookupVBucket",
			Handler:    _ControlPlane_LookupVBucket_Handler,
		},
		{
			MethodName: "CreateVBucket",
			Handler:    _ControlPlane_CreateVBucket_Handler,
		},
		{
			MethodName: "ListVBuckets",
			Handler:    _ControlPlane_ListVBuckets_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenForDeltas",
			Handler:       _ControlPlane_ListenForDeltas_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v1/controlplane.proto",
}
