// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/controlplane.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupCredentialsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	// The response revision MUST be at least this revision. This lets a unary
	// lookup race safely with a newer watch event.
	MinimumRevision uint64 `protobuf:"varint,2,opt,name=minimum_revision,json=minimumRevision,proto3" json:"minimum_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LookupCredentialsRequest) Reset() {
	*x = LookupCredentialsRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupCredentialsRequest) ProtoMessage() {}

func (x *LookupCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupCredentialsRequest.ProtoReflect.Descriptor instead.
func (*LookupCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *LookupCredentialsRequest) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *LookupCredentialsRequest) GetMinimumRevision() uint64 {
	if x != nil {
		return x.MinimumRevision
	}
	return 0
}

// Exactly one result shape is valid. found=true requires secret_key,
// iam_policy_json, and a positive ttl and forbids negative_ttl. found=false
// requires a positive negative_ttl and forbids all positive-result fields.
// revision MUST be at least the request minimum_revision.
type LookupCredentialsResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SecretKey string                 `protobuf:"bytes,1,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	// Required AWS IAM JSON identity policy for this virtual access key.
	IamPolicyJson string               `protobuf:"bytes,2,opt,name=iam_policy_json,json=iamPolicyJson,proto3" json:"iam_policy_json,omitempty"`
	Ttl           *durationpb.Duration `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Found         bool                 `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"`
	NegativeTtl   *durationpb.Duration `protobuf:"bytes,5,opt,name=negative_ttl,json=negativeTtl,proto3" json:"negative_ttl,omitempty"`
	Revision      uint64               `protobuf:"varint,6,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupCredentialsResponse) Reset() {
	*x = LookupCredentialsResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupCredentialsResponse) ProtoMessage() {}

func (x *LookupCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupCredentialsResponse.ProtoReflect.Descriptor instead.
func (*LookupCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *LookupCredentialsResponse) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *LookupCredentialsResponse) GetIamPolicyJson() string {
	if x != nil {
		return x.IamPolicyJson
	}
	return ""
}

func (x *LookupCredentialsResponse) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *LookupCredentialsResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *LookupCredentialsResponse) GetNegativeTtl() *durationpb.Duration {
	if x != nil {
		return x.NegativeTtl
	}
	return nil
}

func (x *LookupCredentialsResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type LookupVBucketRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId     string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	BucketName      string                 `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	MinimumRevision uint64                 `protobuf:"varint,3,opt,name=minimum_revision,json=minimumRevision,proto3" json:"minimum_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LookupVBucketRequest) Reset() {
	*x = LookupVBucketRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupVBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupVBucketRequest) ProtoMessage() {}

func (x *LookupVBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupVBucketRequest.ProtoReflect.Descriptor instead.
func (*LookupVBucketRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *LookupVBucketRequest) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *LookupVBucketRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *LookupVBucketRequest) GetMinimumRevision() uint64 {
	if x != nil {
		return x.MinimumRevision
	}
	return 0
}

// Exactly one result shape is valid. found=true requires a complete valid
// mapping and positive ttl and forbids negative_ttl. found=false requires a
// positive negative_ttl and forbids every positive-result field. revision
// MUST be at least the request minimum_revision.
type LookupVBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealEndpoint  string                 `protobuf:"bytes,1,opt,name=real_endpoint,json=realEndpoint,proto3" json:"real_endpoint,omitempty"`
	RealBucket    string                 `protobuf:"bytes,2,opt,name=real_bucket,json=realBucket,proto3" json:"real_bucket,omitempty"`
	RealAccessKey string                 `protobuf:"bytes,3,opt,name=real_access_key,json=realAccessKey,proto3" json:"real_access_key,omitempty"`
	RealSecretKey string                 `protobuf:"bytes,4,opt,name=real_secret_key,json=realSecretKey,proto3" json:"real_secret_key,omitempty"`
	RealRegion    string                 `protobuf:"bytes,5,opt,name=real_region,json=realRegion,proto3" json:"real_region,omitempty"`
	// The control plane owns namespace allocation. For mappings sharing a real
	// endpoint and bucket, path_prefix values must be normalized and pairwise
	// non-overlapping; an empty prefix reserves the whole real bucket exclusively.
	PathPrefix       string               `protobuf:"bytes,6,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	RealUsePathStyle bool                 `protobuf:"varint,7,opt,name=real_use_path_style,json=realUsePathStyle,proto3" json:"real_use_path_style,omitempty"`
	Ttl              *durationpb.Duration `protobuf:"bytes,8,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Required stable 32-byte random key used only to encrypt mapping-scoped
	// routing tokens. The control plane must keep it unchanged across proxy
	// replicas, restarts, and upstream credential rotation while the real
	// storage namespace is unchanged. The control plane MUST generate a new key
	// whenever real_endpoint, real_bucket, or path_prefix changes. Rotating it
	// invalidates outstanding virtual continuation, upload, and version IDs and
	// therefore requires an explicit drain window.
	RoutingTokenKey []byte               `protobuf:"bytes,9,opt,name=routing_token_key,json=routingTokenKey,proto3" json:"routing_token_key,omitempty"`
	Found           bool                 `protobuf:"varint,10,opt,name=found,proto3" json:"found,omitempty"`
	NegativeTtl     *durationpb.Duration `protobuf:"bytes,11,opt,name=negative_ttl,json=negativeTtl,proto3" json:"negative_ttl,omitempty"`
	Revision        uint64               `protobuf:"varint,12,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LookupVBucketResponse) Reset() {
	*x = LookupVBucketResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupVBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupVBucketResponse) ProtoMessage() {}

func (x *LookupVBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupVBucketResponse.ProtoReflect.Descriptor instead.
func (*LookupVBucketResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *LookupVBucketResponse) GetRealEndpoint() string {
	if x != nil {
		return x.RealEndpoint
	}
	return ""
}

func (x *LookupVBucketResponse) GetRealBucket() string {
	if x != nil {
		return x.RealBucket
	}
	return ""
}

func (x *LookupVBucketResponse) GetRealAccessKey() string {
	if x != nil {
		return x.RealAccessKey
	}
	return ""
}

func (x *LookupVBucketResponse) GetRealSecretKey() string {
	if x != nil {
		return x.RealSecretKey
	}
	return ""
}

func (x *LookupVBucketResponse) GetRealRegion() string {
	if x != nil {
		return x.RealRegion
	}
	return ""
}

func (x *LookupVBucketResponse) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *LookupVBucketResponse) GetRealUsePathStyle() bool {
	if x != nil {
		return x.RealUsePathStyle
	}
	return false
}

func (x *LookupVBucketResponse) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *LookupVBucketResponse) GetRoutingTokenKey() []byte {
	if x != nil {
		return x.RoutingTokenKey
	}
	return nil
}

func (x *LookupVBucketResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *LookupVBucketResponse) GetNegativeTtl() *durationpb.Duration {
	if x != nil {
		return x.NegativeTtl
	}
	return nil
}

func (x *LookupVBucketResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type CreateVBucketRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId        string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	BucketName         string                 `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	LocationConstraint string                 `protobuf:"bytes,3,opt,name=location_constraint,json=locationConstraint,proto3" json:"location_constraint,omitempty"`
	MinimumRevision    uint64                 `protobuf:"varint,4,opt,name=minimum_revision,json=minimumRevision,proto3" json:"minimum_revision,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateVBucketRequest) Reset() {
	*x = CreateVBucketRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVBucketRequest) ProtoMessage() {}

func (x *CreateVBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVBucketRequest.ProtoReflect.Descriptor instead.
func (*CreateVBucketRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVBucketRequest) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *CreateVBucketRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *CreateVBucketRequest) GetLocationConstraint() string {
	if x != nil {
		return x.LocationConstraint
	}
	return ""
}

func (x *CreateVBucketRequest) GetMinimumRevision() uint64 {
	if x != nil {
		return x.MinimumRevision
	}
	return 0
}

type CreateVBucketResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Committed global revision of the create. It MUST be strictly greater than
	// the request minimum_revision. A value ahead of the proxy watch
	// is a successful mutation, not an ambiguous failure: the proxy returns the
	// create success and fails subsequent authorization/routing closed until the
	// watch catches up contiguously to this revision.
	Revision      uint64 `protobuf:"varint,10,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVBucketResponse) Reset() {
	*x = CreateVBucketResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVBucketResponse) ProtoMessage() {}

func (x *CreateVBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVBucketResponse.ProtoReflect.Descriptor instead.
func (*CreateVBucketResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *CreateVBucketResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ListVBucketsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId     string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	MinimumRevision uint64                 `protobuf:"varint,2,opt,name=minimum_revision,json=minimumRevision,proto3" json:"minimum_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListVBucketsRequest) Reset() {
	*x = ListVBucketsRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVBucketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVBucketsRequest) ProtoMessage() {}

func (x *ListVBucketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVBucketsRequest.ProtoReflect.Descriptor instead.
func (*ListVBucketsRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *ListVBucketsRequest) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *ListVBucketsRequest) GetMinimumRevision() uint64 {
	if x != nil {
		return x.MinimumRevision
	}
	return 0
}

type VBucketSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	CreationDate  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VBucketSummary) Reset() {
	*x = VBucketSummary{}
	mi := &file_v1_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VBucketSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VBucketSummary) ProtoMessage() {}

func (x *VBucketSummary) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VBucketSummary.ProtoReflect.Descriptor instead.
func (*VBucketSummary) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *VBucketSummary) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *VBucketSummary) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

type ListVBucketsResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Buckets []*VBucketSummary      `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	// Exact global revision at which the list was evaluated. It MUST be at least
	// the request minimum_revision.
	Revision      uint64 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVBucketsResponse) Reset() {
	*x = ListVBucketsResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVBucketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVBucketsResponse) ProtoMessage() {}

func (x *ListVBucketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVBucketsResponse.ProtoReflect.Descriptor instead.
func (*ListVBucketsResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *ListVBucketsResponse) GetBuckets() []*VBucketSummary {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *ListVBucketsResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type WatchStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque cursor from the most recently accepted synchronization barrier or
	// live event. Empty requests a complete snapshot.
	ResumeCursor  string `protobuf:"bytes,1,opt,name=resume_cursor,json=resumeCursor,proto3" json:"resume_cursor,omitempty"`
	AfterRevision uint64 `protobuf:"varint,2,opt,name=after_revision,json=afterRevision,proto3" json:"after_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchStateRequest) Reset() {
	*x = WatchStateRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStateRequest) ProtoMessage() {}

func (x *WatchStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStateRequest.ProtoReflect.Descriptor instead.
func (*WatchStateRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *WatchStateRequest) GetResumeCursor() string {
	if x != nil {
		return x.ResumeCursor
	}
	return ""
}

func (x *WatchStateRequest) GetAfterRevision() uint64 {
	if x != nil {
		return x.AfterRevision
	}
	return 0
}

type WatchEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*WatchEvent_Credentials
	//	*WatchEvent_BaseHost
	//	*WatchEvent_Vbucket
	//	*WatchEvent_SnapshotBegin
	//	*WatchEvent_SynchronizationBarrier
	//	*WatchEvent_Heartbeat
	Event isWatchEvent_Event `protobuf_oneof:"event"`
	// Global control-plane revision represented by this event. Live mutations are
	// contiguous. Snapshot entry revisions may be sparse and no greater than the
	// following barrier revision.
	Revision uint64 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	// Opaque resume cursor. Required on live events, barriers, and heartbeats.
	// Each persisted revision has exactly one canonical cursor, and each cursor
	// identifies exactly one revision. Restarts and same-cut reset snapshots MUST
	// reproduce that cursor or advance the revision. A live mutation advances both;
	// a barrier or heartbeat repeats the current pair. Duplicate/reordered
	// mutations and forward revision gaps are fatal. A missing/invalid/too-old
	// requested cursor is answered with SnapshotBegin, never a partial replay.
	Cursor        string `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_v1_controlplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{10}
}

func (x *WatchEvent) GetEvent() isWatchEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WatchEvent) GetCredentials() *CredentialsDelta {
	if x != nil {
		if x, ok := x.Event.(*WatchEvent_Credentials); ok {
			return x.Credentials
		}
	}
	return nil
}

func (x *WatchEvent) GetBaseHost() *BaseHostDelta {
	if x != nil {
		if x, ok := x.Event.(*WatchEvent_BaseHost); ok {
			return x.BaseHost
		}
	}
	return nil
}

func (x *WatchEvent) GetVbucket() *VBucketDelta {
	if x != nil {
		if x, ok := x.Event.(*WatchEvent_Vbucket); ok {
			return x.Vbucket
		}
	}
	return nil
}

func (x *WatchEvent) GetSnapshotBegin() *SnapshotBegin {
	if x != nil {
		if x, ok := x.Event.(*WatchEvent_SnapshotBegin); ok {
			return x.SnapshotBegin
		}
	}
	return nil
}

func (x *WatchEvent) GetSynchronizationBarrier() *SynchronizationBarrier {
	if x != nil {
		if x, ok := x.Event.(*WatchEvent_SynchronizationBarrier); ok {
			return x.SynchronizationBarrier
		}
	}
	return nil
}

func (x *WatchEvent) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Event.(*WatchEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WatchEvent) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *WatchEvent) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type isWatchEvent_Event interface {
	isWatchEvent_Event()
}

type WatchEvent_Credentials struct {
	Credentials *CredentialsDelta `protobuf:"bytes,1,opt,name=credentials,proto3,oneof"`
}

type WatchEvent_BaseHost struct {
	BaseHost *BaseHostDelta `protobuf:"bytes,2,opt,name=base_host,json=baseHost,proto3,oneof"`
}

type WatchEvent_Vbucket struct {
	Vbucket *VBucketDelta `protobuf:"bytes,3,opt,name=vbucket,proto3,oneof"`
}

type WatchEvent_SnapshotBegin struct {
	SnapshotBegin *SnapshotBegin `protobuf:"bytes,6,opt,name=snapshot_begin,json=snapshotBegin,proto3,oneof"`
}

type WatchEvent_SynchronizationBarrier struct {
	SynchronizationBarrier *SynchronizationBarrier `protobuf:"bytes,7,opt,name=synchronization_barrier,json=synchronizationBarrier,proto3,oneof"`
}

type WatchEvent_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,8,opt,name=heartbeat,proto3,oneof"`
}

func (*WatchEvent_Credentials) isWatchEvent_Event() {}

func (*WatchEvent_BaseHost) isWatchEvent_Event() {}

func (*WatchEvent_Vbucket) isWatchEvent_Event() {}

func (*WatchEvent_SnapshotBegin) isWatchEvent_Event() {}

func (*WatchEvent_SynchronizationBarrier) isWatchEvent_Event() {}

func (*WatchEvent_Heartbeat) isWatchEvent_Event() {}

// SnapshotBegin retires all credential/vbucket cache state and the base-domain
// registry. It is followed by the complete base-domain snapshot and a
// SynchronizationBarrier at exactly this revision. Credential and vbucket
// snapshot entries are invalid protocol.
type SnapshotBegin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotBegin) Reset() {
	*x = SnapshotBegin{}
	mi := &file_v1_controlplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotBegin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotBegin) ProtoMessage() {}

func (x *SnapshotBegin) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotBegin.ProtoReflect.Descriptor instead.
func (*SnapshotBegin) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{11}
}

// SynchronizationBarrier proves that replay or snapshot state covers exactly
// the envelope revision/cursor pair.
type SynchronizationBarrier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynchronizationBarrier) Reset() {
	*x = SynchronizationBarrier{}
	mi := &file_v1_controlplane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynchronizationBarrier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynchronizationBarrier) ProtoMessage() {}

func (x *SynchronizationBarrier) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynchronizationBarrier.ProtoReflect.Descriptor instead.
func (*SynchronizationBarrier) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{12}
}

// Heartbeat proves the stream is live without mutating state. Its envelope
// repeats the last accepted revision/cursor pair.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_v1_controlplane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{13}
}

// CredentialsDelta never contains a secret or policy. An update invalidates an
// existing hot entry so the next request reloads it at this event's revision;
// it does not populate a cold key. A removal may replace an existing hot entry
// with a negative tombstone for negative_ttl.
type CredentialsDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId   string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	Remove        bool                   `protobuf:"varint,2,opt,name=remove,proto3" json:"remove,omitempty"`
	NegativeTtl   *durationpb.Duration   `protobuf:"bytes,6,opt,name=negative_ttl,json=negativeTtl,proto3" json:"negative_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsDelta) Reset() {
	*x = CredentialsDelta{}
	mi := &file_v1_controlplane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsDelta) ProtoMessage() {}

func (x *CredentialsDelta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsDelta.ProtoReflect.Descriptor instead.
func (*CredentialsDelta) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{14}
}

func (x *CredentialsDelta) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *CredentialsDelta) GetRemove() bool {
	if x != nil {
		return x.Remove
	}
	return false
}

func (x *CredentialsDelta) GetNegativeTtl() *durationpb.Duration {
	if x != nil {
		return x.NegativeTtl
	}
	return nil
}

// BaseHostDelta pushes a base-domain registry update.
// If remove is true, the entry should be evicted. Otherwise it is an upsert.
type BaseHostDelta struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Remove bool                   `protobuf:"varint,2,opt,name=remove,proto3" json:"remove,omitempty"`
	// A normalized base domain, not an observed request hostname. Registry
	// entries live until a watch removal or replacement snapshot; they do not
	// expire independently while the client is synchronized.
	BaseHost      string `protobuf:"bytes,3,opt,name=base_host,json=baseHost,proto3" json:"base_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseHostDelta) Reset() {
	*x = BaseHostDelta{}
	mi := &file_v1_controlplane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseHostDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseHostDelta) ProtoMessage() {}

func (x *BaseHostDelta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseHostDelta.ProtoReflect.Descriptor instead.
func (*BaseHostDelta) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{15}
}

func (x *BaseHostDelta) GetRemove() bool {
	if x != nil {
		return x.Remove
	}
	return false
}

func (x *BaseHostDelta) GetBaseHost() string {
	if x != nil {
		return x.BaseHost
	}
	return ""
}

// VBucketDelta never contains backend credentials or mappings. Update/removal
// behavior matches CredentialsDelta.
type VBucketDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId   string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	BucketName    string                 `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	Remove        bool                   `protobuf:"varint,3,opt,name=remove,proto3" json:"remove,omitempty"`
	NegativeTtl   *durationpb.Duration   `protobuf:"bytes,13,opt,name=negative_ttl,json=negativeTtl,proto3" json:"negative_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VBucketDelta) Reset() {
	*x = VBucketDelta{}
	mi := &file_v1_controlplane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VBucketDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VBucketDelta) ProtoMessage() {}

func (x *VBucketDelta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VBucketDelta.ProtoReflect.Descriptor instead.
func (*VBucketDelta) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{16}
}

func (x *VBucketDelta) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *VBucketDelta) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *VBucketDelta) GetRemove() bool {
	if x != nil {
		return x.Remove
	}
	return false
}

func (x *VBucketDelta) GetNegativeTtl() *durationpb.Duration {
	if x != nil {
		return x.NegativeTtl
	}
	return nil
}

var File_v1_controlplane_proto protoreflect.FileDescriptor

const file_v1_controlplane_proto_rawDesc = "" +
	"\n" +
	"\x15v1/controlplane.proto\x12\vvbuckets.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"i\n" +
	"\x18LookupCredentialsRequest\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12)\n" +
	"\x10minimum_revision\x18\x02 \x01(\x04R\x0fminimumRevision\"\xff\x01\n" +
	"\x19LookupCredentialsResponse\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x01 \x01(\tR\tsecretKey\x12&\n" +
	"\x0fiam_policy_json\x18\x02 \x01(\tR\riamPolicyJson\x12+\n" +
	"\x03ttl\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12\x14\n" +
	"\x05found\x18\x04 \x01(\bR\x05found\x12<\n" +
	"\fnegative_ttl\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\vnegativeTtl\x12\x1a\n" +
	"\brevision\x18\x06 \x01(\x04R\brevision\"\x86\x01\n" +
	"\x14LookupVBucketRequest\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12\x1f\n" +
	"\vbucket_name\x18\x02 \x01(\tR\n" +
	"bucketName\x12)\n" +
	"\x10minimum_revision\x18\x03 \x01(\x04R\x0fminimumRevision\"\xe7\x03\n" +
	"\x15LookupVBucketResponse\x12#\n" +
	"\rreal_endpoint\x18\x01 \x01(\tR\frealEndpoint\x12\x1f\n" +
	"\vreal_bucket\x18\x02 \x01(\tR\n" +
	"realBucket\x12&\n" +
	"\x0freal_access_key\x18\x03 \x01(\tR\rrealAccessKey\x12&\n" +
	"\x0freal_secret_key\x18\x04 \x01(\tR\rrealSecretKey\x12\x1f\n" +
	"\vreal_region\x18\x05 \x01(\tR\n" +
	"realRegion\x12\x1f\n" +
	"\vpath_prefix\x18\x06 \x01(\tR\n" +
	"pathPrefix\x12-\n" +
	"\x13real_use_path_style\x18\a \x01(\bR\x10realUsePathStyle\x12+\n" +
	"\x03ttl\x18\b \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12*\n" +
	"\x11routing_token_key\x18\t \x01(\fR\x0froutingTokenKey\x12\x14\n" +
	"\x05found\x18\n" +
	" \x01(\bR\x05found\x12<\n" +
	"\fnegative_ttl\x18\v \x01(\v2\x19.google.protobuf.DurationR\vnegativeTtl\x12\x1a\n" +
	"\brevision\x18\f \x01(\x04R\brevision\"\xb7\x01\n" +
	"\x14CreateVBucketRequest\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12\x1f\n" +
	"\vbucket_name\x18\x02 \x01(\tR\n" +
	"bucketName\x12/\n" +
	"\x13location_constraint\x18\x03 \x01(\tR\x12locationConstraint\x12)\n" +
	"\x10minimum_revision\x18\x04 \x01(\x04R\x0fminimumRevision\"\xbe\x01\n" +
	"\x15CreateVBucketResponse\x12\x1a\n" +
	"\brevision\x18\n" +
	" \x01(\x04R\brevisionJ\x04\b\x01\x10\n" +
	"R\rreal_endpointR\vreal_bucketR\x0freal_access_keyR\x0freal_secret_keyR\vreal_regionR\vpath_prefixR\x13real_use_path_styleR\x03ttlR\x11routing_token_key\"d\n" +
	"\x13ListVBucketsRequest\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12)\n" +
	"\x10minimum_revision\x18\x02 \x01(\x04R\x0fminimumRevision\"r\n" +
	"\x0eVBucketSummary\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12?\n" +
	"\rcreation_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\"i\n" +
	"\x14ListVBucketsResponse\x125\n" +
	"\abuckets\x18\x01 \x03(\v2\x1b.vbuckets.v1.VBucketSummaryR\abuckets\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\"_\n" +
	"\x11WatchStateRequest\x12#\n" +
	"\rresume_cursor\x18\x01 \x01(\tR\fresumeCursor\x12%\n" +
	"\x0eafter_revision\x18\x02 \x01(\x04R\rafterRevision\"\xdb\x03\n" +
	"\n" +
	"WatchEvent\x12A\n" +
	"\vcredentials\x18\x01 \x01(\v2\x1d.vbuckets.v1.CredentialsDeltaH\x00R\vcredentials\x129\n" +
	"\tbase_host\x18\x02 \x01(\v2\x1a.vbuckets.v1.BaseHostDeltaH\x00R\bbaseHost\x125\n" +
	"\avbucket\x18\x03 \x01(\v2\x19.vbuckets.v1.VBucketDeltaH\x00R\avbucket\x12C\n" +
	"\x0esnapshot_begin\x18\x06 \x01(\v2\x1a.vbuckets.v1.SnapshotBeginH\x00R\rsnapshotBegin\x12^\n" +
	"\x17synchronization_barrier\x18\a \x01(\v2#.vbuckets.v1.SynchronizationBarrierH\x00R\x16synchronizationBarrier\x126\n" +
	"\theartbeat\x18\b \x01(\v2\x16.vbuckets.v1.HeartbeatH\x00R\theartbeat\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursorB\a\n" +
	"\x05event\"\x0f\n" +
	"\rSnapshotBegin\"\x18\n" +
	"\x16SynchronizationBarrier\"\v\n" +
	"\tHeartbeat\"\xb4\x01\n" +
	"\x10CredentialsDelta\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12\x16\n" +
	"\x06remove\x18\x02 \x01(\bR\x06remove\x12<\n" +
	"\fnegative_ttl\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\vnegativeTtlJ\x04\b\x03\x10\x06R\n" +
	"secret_keyR\x0fiam_policy_jsonR\x03ttl\"l\n" +
	"\rBaseHostDelta\x12\x16\n" +
	"\x06remove\x18\x02 \x01(\bR\x06remove\x12\x1b\n" +
	"\tbase_host\x18\x03 \x01(\tR\bbaseHostJ\x04\b\x01\x10\x02J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06R\bhostnameR\x05foundR\x03ttl\"\xb4\x02\n" +
	"\fVBucketDelta\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12\x1f\n" +
	"\vbucket_name\x18\x02 \x01(\tR\n" +
	"bucketName\x12\x16\n" +
	"\x06remove\x18\x03 \x01(\bR\x06remove\x12<\n" +
	"\fnegative_ttl\x18\r \x01(\v2\x19.google.protobuf.DurationR\vnegativeTtlJ\x04\b\x04\x10\rR\rreal_endpointR\vreal_bucketR\x0freal_access_keyR\x0freal_secret_keyR\vreal_regionR\vpath_prefixR\x13real_use_path_styleR\x03ttlR\x11routing_token_key2\xc0\x03\n" +
	"\fControlPlane\x12b\n" +
	"\x11LookupCredentials\x12%.vbuckets.v1.LookupCredentialsRequest\x1a&.vbuckets.v1.LookupCredentialsResponse\x12V\n" +
	"\rLookupVBucket\x12!.vbuckets.v1.LookupVBucketRequest\x1a\".vbuckets.v1.LookupVBucketResponse\x12V\n" +
	"\rCreateVBucket\x12!.vbuckets.v1.CreateVBucketRequest\x1a\".vbuckets.v1.CreateVBucketResponse\x12S\n" +
	"\fListVBuckets\x12 .vbuckets.v1.ListVBucketsRequest\x1a!.vbuckets.v1.ListVBucketsResponse\x12G\n" +
	"\n" +
	"WatchState\x12\x1e.vbuckets.v1.WatchStateRequest\x1a\x17.vbuckets.v1.WatchEvent0\x01B1Z/github.com/danthegoodman1/vbuckets/api/v1;apiv1b\x06proto3"

var (
	file_v1_controlplane_proto_rawDescOnce sync.Once
	file_v1_controlplane_proto_rawDescData []byte
)

func file_v1_controlplane_proto_rawDescGZIP() []byte {
	file_v1_controlplane_proto_rawDescOnce.Do(func() {
		file_v1_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_controlplane_proto_rawDesc), len(file_v1_controlplane_proto_rawDesc)))
	})
	return file_v1_controlplane_proto_rawDescData
}

var file_v1_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_v1_controlplane_proto_goTypes = []any{
	(*LookupCredentialsRequest)(nil),  // 0: vbuckets.v1.LookupCredentialsRequest
	(*LookupCredentialsResponse)(nil), // 1: vbuckets.v1.LookupCredentialsResponse
	(*LookupVBucketRequest)(nil),      // 2: vbuckets.v1.LookupVBucketRequest
	(*LookupVBucketResponse)(nil),     // 3: vbuckets.v1.LookupVBucketResponse
	(*CreateVBucketRequest)(nil),      // 4: vbuckets.v1.CreateVBucketRequest
	(*CreateVBucketResponse)(nil),     // 5: vbuckets.v1.CreateVBucketResponse
	(*ListVBucketsRequest)(nil),       // 6: vbuckets.v1.ListVBucketsRequest
	(*VBucketSummary)(nil),            // 7: vbuckets.v1.VBucketSummary
	(*ListVBucketsResponse)(nil),      // 8: vbuckets.v1.ListVBucketsResponse
	(*WatchStateRequest)(nil),         // 9: vbuckets.v1.WatchStateRequest
	(*WatchEvent)(nil),                // 10: vbuckets.v1.WatchEvent
	(*SnapshotBegin)(nil),             // 11: vbuckets.v1.SnapshotBegin
	(*SynchronizationBarrier)(nil),    // 12: vbuckets.v1.SynchronizationBarrier
	(*Heartbeat)(nil),                 // 13: vbuckets.v1.Heartbeat
	(*CredentialsDelta)(nil),          // 14: vbuckets.v1.CredentialsDelta
	(*BaseHostDelta)(nil),             // 15: vbuckets.v1.BaseHostDelta
	(*VBucketDelta)(nil),              // 16: vbuckets.v1.VBucketDelta
	(*durationpb.Duration)(nil),       // 17: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),     // 18: google.protobuf.Timestamp
}
var file_v1_controlplane_proto_depIdxs = []int32{
	17, // 0: vbuckets.v1.LookupCredentialsResponse.ttl:type_name -> google.protobuf.Duration
	17, // 1: vbuckets.v1.LookupCredentialsResponse.negative_ttl:type_name -> google.protobuf.Duration
	17, // 2: vbuckets.v1.LookupVBucketResponse.ttl:type_name -> google.protobuf.Duration
	17, // 3: vbuckets.v1.LookupVBucketResponse.negative_ttl:type_name -> google.protobuf.Duration
	18, // 4: vbuckets.v1.VBucketSummary.creation_date:type_name -> google.protobuf.Timestamp
	7,  // 5: vbuckets.v1.ListVBucketsResponse.buckets:type_name -> vbuckets.v1.VBucketSummary
	14, // 6: vbuckets.v1.WatchEvent.credentials:type_name -> vbuckets.v1.CredentialsDelta
	15, // 7: vbuckets.v1.WatchEvent.base_host:type_name -> vbuckets.v1.BaseHostDelta
	16, // 8: vbuckets.v1.WatchEvent.vbucket:type_name -> vbuckets.v1.VBucketDelta
	11, // 9: vbuckets.v1.WatchEvent.snapshot_begin:type_name -> vbuckets.v1.SnapshotBegin
	12, // 10: vbuckets.v1.WatchEvent.synchronization_barrier:type_name -> vbuckets.v1.SynchronizationBarrier
	13, // 11: vbuckets.v1.WatchEvent.heartbeat:type_name -> vbuckets.v1.Heartbeat
	17, // 12: vbuckets.v1.CredentialsDelta.negative_ttl:type_name -> google.protobuf.Duration
	17, // 13: vbuckets.v1.VBucketDelta.negative_ttl:type_name -> google.protobuf.Duration
	0,  // 14: vbuckets.v1.ControlPlane.LookupCredentials:input_type -> vbuckets.v1.LookupCredentialsRequest
	2,  // 15: vbuckets.v1.ControlPlane.LookupVBucket:input_type -> vbuckets.v1.LookupVBucketRequest
	4,  // 16: vbuckets.v1.ControlPlane.CreateVBucket:input_type -> vbuckets.v1.CreateVBucketRequest
	6,  // 17: vbuckets.v1.ControlPlane.ListVBuckets:input_type -> vbuckets.v1.ListVBucketsRequest
	9,  // 18: vbuckets.v1.ControlPlane.WatchState:input_type -> vbuckets.v1.WatchStateRequest
	1,  // 19: vbuckets.v1.ControlPlane.LookupCredentials:output_type -> vbuckets.v1.LookupCredentialsResponse
	3,  // 20: vbuckets.v1.ControlPlane.LookupVBucket:output_type -> vbuckets.v1.LookupVBucketResponse
	5,  // 21: vbuckets.v1.ControlPlane.CreateVBucket:output_type -> vbuckets.v1.CreateVBucketResponse
	8,  // 22: vbuckets.v1.ControlPlane.ListVBuckets:output_type -> vbuckets.v1.ListVBucketsResponse
	10, // 23: vbuckets.v1.ControlPlane.WatchState:output_type -> vbuckets.v1.WatchEvent
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_v1_controlplane_proto_init() }
func file_v1_controlplane_proto_init() {
	if File_v1_controlplane_proto != nil {
		return
	}
	file_v1_controlplane_proto_msgTypes[10].OneofWrappers = []any{
		(*WatchEvent_Credentials)(nil),
		(*WatchEvent_BaseHost)(nil),
		(*WatchEvent_Vbucket)(nil),
		(*WatchEvent_SnapshotBegin)(nil),
		(*WatchEvent_SynchronizationBarrier)(nil),
		(*WatchEvent_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_controlplane_proto_rawDesc), len(file_v1_controlplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_controlplane_proto_goTypes,
		DependencyIndexes: file_v1_controlplane_proto_depIdxs,
		MessageInfos:      file_v1_controlplane_proto_msgTypes,
	}.Build()
	File_v1_controlplane_proto = out.File
	file_v1_controlplane_proto_goTypes = nil
	file_v1_controlplane_proto_depIdxs = nil
}
