// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/controlplane.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId   string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupCredentialsRequest) Reset() {
	*x = LookupCredentialsRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupCredentialsRequest) ProtoMessage() {}

func (x *LookupCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupCredentialsRequest.ProtoReflect.Descriptor instead.
func (*LookupCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *LookupCredentialsRequest) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

type LookupCredentialsResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SecretKey string                 `protobuf:"bytes,1,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	// Required AWS IAM JSON identity policy for this virtual access key.
	IamPolicyJson string               `protobuf:"bytes,2,opt,name=iam_policy_json,json=iamPolicyJson,proto3" json:"iam_policy_json,omitempty"`
	Ttl           *durationpb.Duration `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupCredentialsResponse) Reset() {
	*x = LookupCredentialsResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupCredentialsResponse) ProtoMessage() {}

func (x *LookupCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupCredentialsResponse.ProtoReflect.Descriptor instead.
func (*LookupCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *LookupCredentialsResponse) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *LookupCredentialsResponse) GetIamPolicyJson() string {
	if x != nil {
		return x.IamPolicyJson
	}
	return ""
}

func (x *LookupCredentialsResponse) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type LookupBaseHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupBaseHostRequest) Reset() {
	*x = LookupBaseHostRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupBaseHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupBaseHostRequest) ProtoMessage() {}

func (x *LookupBaseHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupBaseHostRequest.ProtoReflect.Descriptor instead.
func (*LookupBaseHostRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *LookupBaseHostRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type LookupBaseHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseHost      string                 `protobuf:"bytes,1,opt,name=base_host,json=baseHost,proto3" json:"base_host,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupBaseHostResponse) Reset() {
	*x = LookupBaseHostResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupBaseHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupBaseHostResponse) ProtoMessage() {}

func (x *LookupBaseHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupBaseHostResponse.ProtoReflect.Descriptor instead.
func (*LookupBaseHostResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *LookupBaseHostResponse) GetBaseHost() string {
	if x != nil {
		return x.BaseHost
	}
	return ""
}

func (x *LookupBaseHostResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *LookupBaseHostResponse) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type LookupVBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId   string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	BucketName    string                 `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupVBucketRequest) Reset() {
	*x = LookupVBucketRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupVBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupVBucketRequest) ProtoMessage() {}

func (x *LookupVBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupVBucketRequest.ProtoReflect.Descriptor instead.
func (*LookupVBucketRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *LookupVBucketRequest) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *LookupVBucketRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type LookupVBucketResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RealEndpoint     string                 `protobuf:"bytes,1,opt,name=real_endpoint,json=realEndpoint,proto3" json:"real_endpoint,omitempty"`
	RealBucket       string                 `protobuf:"bytes,2,opt,name=real_bucket,json=realBucket,proto3" json:"real_bucket,omitempty"`
	RealAccessKey    string                 `protobuf:"bytes,3,opt,name=real_access_key,json=realAccessKey,proto3" json:"real_access_key,omitempty"`
	RealSecretKey    string                 `protobuf:"bytes,4,opt,name=real_secret_key,json=realSecretKey,proto3" json:"real_secret_key,omitempty"`
	RealRegion       string                 `protobuf:"bytes,5,opt,name=real_region,json=realRegion,proto3" json:"real_region,omitempty"`
	PathPrefix       string                 `protobuf:"bytes,6,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	RealUsePathStyle bool                   `protobuf:"varint,7,opt,name=real_use_path_style,json=realUsePathStyle,proto3" json:"real_use_path_style,omitempty"`
	Ttl              *durationpb.Duration   `protobuf:"bytes,8,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LookupVBucketResponse) Reset() {
	*x = LookupVBucketResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupVBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupVBucketResponse) ProtoMessage() {}

func (x *LookupVBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupVBucketResponse.ProtoReflect.Descriptor instead.
func (*LookupVBucketResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *LookupVBucketResponse) GetRealEndpoint() string {
	if x != nil {
		return x.RealEndpoint
	}
	return ""
}

func (x *LookupVBucketResponse) GetRealBucket() string {
	if x != nil {
		return x.RealBucket
	}
	return ""
}

func (x *LookupVBucketResponse) GetRealAccessKey() string {
	if x != nil {
		return x.RealAccessKey
	}
	return ""
}

func (x *LookupVBucketResponse) GetRealSecretKey() string {
	if x != nil {
		return x.RealSecretKey
	}
	return ""
}

func (x *LookupVBucketResponse) GetRealRegion() string {
	if x != nil {
		return x.RealRegion
	}
	return ""
}

func (x *LookupVBucketResponse) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *LookupVBucketResponse) GetRealUsePathStyle() bool {
	if x != nil {
		return x.RealUsePathStyle
	}
	return false
}

func (x *LookupVBucketResponse) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type CreateVBucketRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId        string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	BucketName         string                 `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	LocationConstraint string                 `protobuf:"bytes,3,opt,name=location_constraint,json=locationConstraint,proto3" json:"location_constraint,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateVBucketRequest) Reset() {
	*x = CreateVBucketRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVBucketRequest) ProtoMessage() {}

func (x *CreateVBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVBucketRequest.ProtoReflect.Descriptor instead.
func (*CreateVBucketRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *CreateVBucketRequest) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *CreateVBucketRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *CreateVBucketRequest) GetLocationConstraint() string {
	if x != nil {
		return x.LocationConstraint
	}
	return ""
}

type CreateVBucketResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RealEndpoint     string                 `protobuf:"bytes,1,opt,name=real_endpoint,json=realEndpoint,proto3" json:"real_endpoint,omitempty"`
	RealBucket       string                 `protobuf:"bytes,2,opt,name=real_bucket,json=realBucket,proto3" json:"real_bucket,omitempty"`
	RealAccessKey    string                 `protobuf:"bytes,3,opt,name=real_access_key,json=realAccessKey,proto3" json:"real_access_key,omitempty"`
	RealSecretKey    string                 `protobuf:"bytes,4,opt,name=real_secret_key,json=realSecretKey,proto3" json:"real_secret_key,omitempty"`
	RealRegion       string                 `protobuf:"bytes,5,opt,name=real_region,json=realRegion,proto3" json:"real_region,omitempty"`
	PathPrefix       string                 `protobuf:"bytes,6,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	RealUsePathStyle bool                   `protobuf:"varint,7,opt,name=real_use_path_style,json=realUsePathStyle,proto3" json:"real_use_path_style,omitempty"`
	Ttl              *durationpb.Duration   `protobuf:"bytes,8,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateVBucketResponse) Reset() {
	*x = CreateVBucketResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVBucketResponse) ProtoMessage() {}

func (x *CreateVBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVBucketResponse.ProtoReflect.Descriptor instead.
func (*CreateVBucketResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *CreateVBucketResponse) GetRealEndpoint() string {
	if x != nil {
		return x.RealEndpoint
	}
	return ""
}

func (x *CreateVBucketResponse) GetRealBucket() string {
	if x != nil {
		return x.RealBucket
	}
	return ""
}

func (x *CreateVBucketResponse) GetRealAccessKey() string {
	if x != nil {
		return x.RealAccessKey
	}
	return ""
}

func (x *CreateVBucketResponse) GetRealSecretKey() string {
	if x != nil {
		return x.RealSecretKey
	}
	return ""
}

func (x *CreateVBucketResponse) GetRealRegion() string {
	if x != nil {
		return x.RealRegion
	}
	return ""
}

func (x *CreateVBucketResponse) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *CreateVBucketResponse) GetRealUsePathStyle() bool {
	if x != nil {
		return x.RealUsePathStyle
	}
	return false
}

func (x *CreateVBucketResponse) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type ListVBucketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId   string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVBucketsRequest) Reset() {
	*x = ListVBucketsRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVBucketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVBucketsRequest) ProtoMessage() {}

func (x *ListVBucketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVBucketsRequest.ProtoReflect.Descriptor instead.
func (*ListVBucketsRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *ListVBucketsRequest) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

type VBucketSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	CreationDate  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VBucketSummary) Reset() {
	*x = VBucketSummary{}
	mi := &file_v1_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VBucketSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VBucketSummary) ProtoMessage() {}

func (x *VBucketSummary) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VBucketSummary.ProtoReflect.Descriptor instead.
func (*VBucketSummary) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *VBucketSummary) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *VBucketSummary) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

type ListVBucketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*VBucketSummary      `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVBucketsResponse) Reset() {
	*x = ListVBucketsResponse{}
	mi := &file_v1_controlplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVBucketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVBucketsResponse) ProtoMessage() {}

func (x *ListVBucketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVBucketsResponse.ProtoReflect.Descriptor instead.
func (*ListVBucketsResponse) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{10}
}

func (x *ListVBucketsResponse) GetBuckets() []*VBucketSummary {
	if x != nil {
		return x.Buckets
	}
	return nil
}

type ListenForDeltasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenForDeltasRequest) Reset() {
	*x = ListenForDeltasRequest{}
	mi := &file_v1_controlplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenForDeltasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenForDeltasRequest) ProtoMessage() {}

func (x *ListenForDeltasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenForDeltasRequest.ProtoReflect.Descriptor instead.
func (*ListenForDeltasRequest) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{11}
}

type Delta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Delta:
	//
	//	*Delta_Credentials
	//	*Delta_BaseHost
	//	*Delta_Vbucket
	Delta         isDelta_Delta `protobuf_oneof:"delta"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_v1_controlplane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{12}
}

func (x *Delta) GetDelta() isDelta_Delta {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *Delta) GetCredentials() *CredentialsDelta {
	if x != nil {
		if x, ok := x.Delta.(*Delta_Credentials); ok {
			return x.Credentials
		}
	}
	return nil
}

func (x *Delta) GetBaseHost() *BaseHostDelta {
	if x != nil {
		if x, ok := x.Delta.(*Delta_BaseHost); ok {
			return x.BaseHost
		}
	}
	return nil
}

func (x *Delta) GetVbucket() *VBucketDelta {
	if x != nil {
		if x, ok := x.Delta.(*Delta_Vbucket); ok {
			return x.Vbucket
		}
	}
	return nil
}

type isDelta_Delta interface {
	isDelta_Delta()
}

type Delta_Credentials struct {
	Credentials *CredentialsDelta `protobuf:"bytes,1,opt,name=credentials,proto3,oneof"`
}

type Delta_BaseHost struct {
	BaseHost *BaseHostDelta `protobuf:"bytes,2,opt,name=base_host,json=baseHost,proto3,oneof"`
}

type Delta_Vbucket struct {
	Vbucket *VBucketDelta `protobuf:"bytes,3,opt,name=vbucket,proto3,oneof"`
}

func (*Delta_Credentials) isDelta_Delta() {}

func (*Delta_BaseHost) isDelta_Delta() {}

func (*Delta_Vbucket) isDelta_Delta() {}

// CredentialsDelta pushes a credential cache update.
// If remove is true, the entry should be evicted. Otherwise it is an upsert.
type CredentialsDelta struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	Remove      bool                   `protobuf:"varint,2,opt,name=remove,proto3" json:"remove,omitempty"`
	// Fields below are only set on upsert (remove == false).
	SecretKey     string               `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	IamPolicyJson string               `protobuf:"bytes,4,opt,name=iam_policy_json,json=iamPolicyJson,proto3" json:"iam_policy_json,omitempty"`
	Ttl           *durationpb.Duration `protobuf:"bytes,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsDelta) Reset() {
	*x = CredentialsDelta{}
	mi := &file_v1_controlplane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsDelta) ProtoMessage() {}

func (x *CredentialsDelta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsDelta.ProtoReflect.Descriptor instead.
func (*CredentialsDelta) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{13}
}

func (x *CredentialsDelta) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *CredentialsDelta) GetRemove() bool {
	if x != nil {
		return x.Remove
	}
	return false
}

func (x *CredentialsDelta) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *CredentialsDelta) GetIamPolicyJson() string {
	if x != nil {
		return x.IamPolicyJson
	}
	return ""
}

func (x *CredentialsDelta) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

// BaseHostDelta pushes a base host cache update.
// If remove is true, the entry should be evicted. Otherwise it is an upsert.
type BaseHostDelta struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Hostname string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Remove   bool                   `protobuf:"varint,2,opt,name=remove,proto3" json:"remove,omitempty"`
	// Fields below are only set on upsert (remove == false).
	BaseHost      string               `protobuf:"bytes,3,opt,name=base_host,json=baseHost,proto3" json:"base_host,omitempty"`
	Found         bool                 `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"`
	Ttl           *durationpb.Duration `protobuf:"bytes,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseHostDelta) Reset() {
	*x = BaseHostDelta{}
	mi := &file_v1_controlplane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseHostDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseHostDelta) ProtoMessage() {}

func (x *BaseHostDelta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseHostDelta.ProtoReflect.Descriptor instead.
func (*BaseHostDelta) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{14}
}

func (x *BaseHostDelta) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *BaseHostDelta) GetRemove() bool {
	if x != nil {
		return x.Remove
	}
	return false
}

func (x *BaseHostDelta) GetBaseHost() string {
	if x != nil {
		return x.BaseHost
	}
	return ""
}

func (x *BaseHostDelta) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *BaseHostDelta) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

// VBucketDelta pushes a vbucket mapping cache update.
// If remove is true, the entry should be evicted. Otherwise it is an upsert.
type VBucketDelta struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	BucketName  string                 `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	Remove      bool                   `protobuf:"varint,3,opt,name=remove,proto3" json:"remove,omitempty"`
	// Fields below are only set on upsert (remove == false).
	RealEndpoint     string               `protobuf:"bytes,4,opt,name=real_endpoint,json=realEndpoint,proto3" json:"real_endpoint,omitempty"`
	RealBucket       string               `protobuf:"bytes,5,opt,name=real_bucket,json=realBucket,proto3" json:"real_bucket,omitempty"`
	RealAccessKey    string               `protobuf:"bytes,6,opt,name=real_access_key,json=realAccessKey,proto3" json:"real_access_key,omitempty"`
	RealSecretKey    string               `protobuf:"bytes,7,opt,name=real_secret_key,json=realSecretKey,proto3" json:"real_secret_key,omitempty"`
	RealRegion       string               `protobuf:"bytes,8,opt,name=real_region,json=realRegion,proto3" json:"real_region,omitempty"`
	PathPrefix       string               `protobuf:"bytes,9,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	RealUsePathStyle bool                 `protobuf:"varint,10,opt,name=real_use_path_style,json=realUsePathStyle,proto3" json:"real_use_path_style,omitempty"`
	Ttl              *durationpb.Duration `protobuf:"bytes,11,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VBucketDelta) Reset() {
	*x = VBucketDelta{}
	mi := &file_v1_controlplane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VBucketDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VBucketDelta) ProtoMessage() {}

func (x *VBucketDelta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_controlplane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VBucketDelta.ProtoReflect.Descriptor instead.
func (*VBucketDelta) Descriptor() ([]byte, []int) {
	return file_v1_controlplane_proto_rawDescGZIP(), []int{15}
}

func (x *VBucketDelta) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *VBucketDelta) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *VBucketDelta) GetRemove() bool {
	if x != nil {
		return x.Remove
	}
	return false
}

func (x *VBucketDelta) GetRealEndpoint() string {
	if x != nil {
		return x.RealEndpoint
	}
	return ""
}

func (x *VBucketDelta) GetRealBucket() string {
	if x != nil {
		return x.RealBucket
	}
	return ""
}

func (x *VBucketDelta) GetRealAccessKey() string {
	if x != nil {
		return x.RealAccessKey
	}
	return ""
}

func (x *VBucketDelta) GetRealSecretKey() string {
	if x != nil {
		return x.RealSecretKey
	}
	return ""
}

func (x *VBucketDelta) GetRealRegion() string {
	if x != nil {
		return x.RealRegion
	}
	return ""
}

func (x *VBucketDelta) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *VBucketDelta) GetRealUsePathStyle() bool {
	if x != nil {
		return x.RealUsePathStyle
	}
	return false
}

func (x *VBucketDelta) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

var File_v1_controlplane_proto protoreflect.FileDescriptor

const file_v1_controlplane_proto_rawDesc = "" +
	"\n" +
	"\x15v1/controlplane.proto\x12\vvbuckets.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\">\n" +
	"\x18LookupCredentialsRequest\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\"\x8f\x01\n" +
	"\x19LookupCredentialsResponse\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x01 \x01(\tR\tsecretKey\x12&\n" +
	"\x0fiam_policy_json\x18\x02 \x01(\tR\riamPolicyJson\x12+\n" +
	"\x03ttl\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"3\n" +
	"\x15LookupBaseHostRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"x\n" +
	"\x16LookupBaseHostResponse\x12\x1b\n" +
	"\tbase_host\x18\x01 \x01(\tR\bbaseHost\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12+\n" +
	"\x03ttl\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"[\n" +
	"\x14LookupVBucketRequest\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12\x1f\n" +
	"\vbucket_name\x18\x02 \x01(\tR\n" +
	"bucketName\"\xcb\x02\n" +
	"\x15LookupVBucketResponse\x12#\n" +
	"\rreal_endpoint\x18\x01 \x01(\tR\frealEndpoint\x12\x1f\n" +
	"\vreal_bucket\x18\x02 \x01(\tR\n" +
	"realBucket\x12&\n" +
	"\x0freal_access_key\x18\x03 \x01(\tR\rrealAccessKey\x12&\n" +
	"\x0freal_secret_key\x18\x04 \x01(\tR\rrealSecretKey\x12\x1f\n" +
	"\vreal_region\x18\x05 \x01(\tR\n" +
	"realRegion\x12\x1f\n" +
	"\vpath_prefix\x18\x06 \x01(\tR\n" +
	"pathPrefix\x12-\n" +
	"\x13real_use_path_style\x18\a \x01(\bR\x10realUsePathStyle\x12+\n" +
	"\x03ttl\x18\b \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"\x8c\x01\n" +
	"\x14CreateVBucketRequest\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12\x1f\n" +
	"\vbucket_name\x18\x02 \x01(\tR\n" +
	"bucketName\x12/\n" +
	"\x13location_constraint\x18\x03 \x01(\tR\x12locationConstraint\"\xcb\x02\n" +
	"\x15CreateVBucketResponse\x12#\n" +
	"\rreal_endpoint\x18\x01 \x01(\tR\frealEndpoint\x12\x1f\n" +
	"\vreal_bucket\x18\x02 \x01(\tR\n" +
	"realBucket\x12&\n" +
	"\x0freal_access_key\x18\x03 \x01(\tR\rrealAccessKey\x12&\n" +
	"\x0freal_secret_key\x18\x04 \x01(\tR\rrealSecretKey\x12\x1f\n" +
	"\vreal_region\x18\x05 \x01(\tR\n" +
	"realRegion\x12\x1f\n" +
	"\vpath_prefix\x18\x06 \x01(\tR\n" +
	"pathPrefix\x12-\n" +
	"\x13real_use_path_style\x18\a \x01(\bR\x10realUsePathStyle\x12+\n" +
	"\x03ttl\x18\b \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"9\n" +
	"\x13ListVBucketsRequest\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\"r\n" +
	"\x0eVBucketSummary\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12?\n" +
	"\rcreation_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\"M\n" +
	"\x14ListVBucketsResponse\x125\n" +
	"\abuckets\x18\x01 \x03(\v2\x1b.vbuckets.v1.VBucketSummaryR\abuckets\"\x18\n" +
	"\x16ListenForDeltasRequest\"\xc5\x01\n" +
	"\x05Delta\x12A\n" +
	"\vcredentials\x18\x01 \x01(\v2\x1d.vbuckets.v1.CredentialsDeltaH\x00R\vcredentials\x129\n" +
	"\tbase_host\x18\x02 \x01(\v2\x1a.vbuckets.v1.BaseHostDeltaH\x00R\bbaseHost\x125\n" +
	"\avbucket\x18\x03 \x01(\v2\x19.vbuckets.v1.VBucketDeltaH\x00R\avbucketB\a\n" +
	"\x05delta\"\xc2\x01\n" +
	"\x10CredentialsDelta\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12\x16\n" +
	"\x06remove\x18\x02 \x01(\bR\x06remove\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x03 \x01(\tR\tsecretKey\x12&\n" +
	"\x0fiam_policy_json\x18\x04 \x01(\tR\riamPolicyJson\x12+\n" +
	"\x03ttl\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"\xa3\x01\n" +
	"\rBaseHostDelta\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x16\n" +
	"\x06remove\x18\x02 \x01(\bR\x06remove\x12\x1b\n" +
	"\tbase_host\x18\x03 \x01(\tR\bbaseHost\x12\x14\n" +
	"\x05found\x18\x04 \x01(\bR\x05found\x12+\n" +
	"\x03ttl\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"\x9f\x03\n" +
	"\fVBucketDelta\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12\x1f\n" +
	"\vbucket_name\x18\x02 \x01(\tR\n" +
	"bucketName\x12\x16\n" +
	"\x06remove\x18\x03 \x01(\bR\x06remove\x12#\n" +
	"\rreal_endpoint\x18\x04 \x01(\tR\frealEndpoint\x12\x1f\n" +
	"\vreal_bucket\x18\x05 \x01(\tR\n" +
	"realBucket\x12&\n" +
	"\x0freal_access_key\x18\x06 \x01(\tR\rrealAccessKey\x12&\n" +
	"\x0freal_secret_key\x18\a \x01(\tR\rrealSecretKey\x12\x1f\n" +
	"\vreal_region\x18\b \x01(\tR\n" +
	"realRegion\x12\x1f\n" +
	"\vpath_prefix\x18\t \x01(\tR\n" +
	"pathPrefix\x12-\n" +
	"\x13real_use_path_style\x18\n" +
	" \x01(\bR\x10realUsePathStyle\x12+\n" +
	"\x03ttl\x18\v \x01(\v2\x19.google.protobuf.DurationR\x03ttl2\xa0\x04\n" +
	"\fControlPlane\x12b\n" +
	"\x11LookupCredentials\x12%.vbuckets.v1.LookupCredentialsRequest\x1a&.vbuckets.v1.LookupCredentialsResponse\x12Y\n" +
	"\x0eLookupBaseHost\x12\".vbuckets.v1.LookupBaseHostRequest\x1a#.vbuckets.v1.LookupBaseHostResponse\x12V\n" +
	"\rLookupVBucket\x12!.vbuckets.v1.LookupVBucketRequest\x1a\".vbuckets.v1.LookupVBucketResponse\x12V\n" +
	"\rCreateVBucket\x12!.vbuckets.v1.CreateVBucketRequest\x1a\".vbuckets.v1.CreateVBucketResponse\x12S\n" +
	"\fListVBuckets\x12 .vbuckets.v1.ListVBucketsRequest\x1a!.vbuckets.v1.ListVBucketsResponse\x12L\n" +
	"\x0fListenForDeltas\x12#.vbuckets.v1.ListenForDeltasRequest\x1a\x12.vbuckets.v1.Delta0\x01B1Z/github.com/danthegoodman1/vbuckets/api/v1;apiv1b\x06proto3"

var (
	file_v1_controlplane_proto_rawDescOnce sync.Once
	file_v1_controlplane_proto_rawDescData []byte
)

func file_v1_controlplane_proto_rawDescGZIP() []byte {
	file_v1_controlplane_proto_rawDescOnce.Do(func() {
		file_v1_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_controlplane_proto_rawDesc), len(file_v1_controlplane_proto_rawDesc)))
	})
	return file_v1_controlplane_proto_rawDescData
}

var file_v1_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_v1_controlplane_proto_goTypes = []any{
	(*LookupCredentialsRequest)(nil),  // 0: vbuckets.v1.LookupCredentialsRequest
	(*LookupCredentialsResponse)(nil), // 1: vbuckets.v1.LookupCredentialsResponse
	(*LookupBaseHostRequest)(nil),     // 2: vbuckets.v1.LookupBaseHostRequest
	(*LookupBaseHostResponse)(nil),    // 3: vbuckets.v1.LookupBaseHostResponse
	(*LookupVBucketRequest)(nil),      // 4: vbuckets.v1.LookupVBucketRequest
	(*LookupVBucketResponse)(nil),     // 5: vbuckets.v1.LookupVBucketResponse
	(*CreateVBucketRequest)(nil),      // 6: vbuckets.v1.CreateVBucketRequest
	(*CreateVBucketResponse)(nil),     // 7: vbuckets.v1.CreateVBucketResponse
	(*ListVBucketsRequest)(nil),       // 8: vbuckets.v1.ListVBucketsRequest
	(*VBucketSummary)(nil),            // 9: vbuckets.v1.VBucketSummary
	(*ListVBucketsResponse)(nil),      // 10: vbuckets.v1.ListVBucketsResponse
	(*ListenForDeltasRequest)(nil),    // 11: vbuckets.v1.ListenForDeltasRequest
	(*Delta)(nil),                     // 12: vbuckets.v1.Delta
	(*CredentialsDelta)(nil),          // 13: vbuckets.v1.CredentialsDelta
	(*BaseHostDelta)(nil),             // 14: vbuckets.v1.BaseHostDelta
	(*VBucketDelta)(nil),              // 15: vbuckets.v1.VBucketDelta
	(*durationpb.Duration)(nil),       // 16: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),     // 17: google.protobuf.Timestamp
}
var file_v1_controlplane_proto_depIdxs = []int32{
	16, // 0: vbuckets.v1.LookupCredentialsResponse.ttl:type_name -> google.protobuf.Duration
	16, // 1: vbuckets.v1.LookupBaseHostResponse.ttl:type_name -> google.protobuf.Duration
	16, // 2: vbuckets.v1.LookupVBucketResponse.ttl:type_name -> google.protobuf.Duration
	16, // 3: vbuckets.v1.CreateVBucketResponse.ttl:type_name -> google.protobuf.Duration
	17, // 4: vbuckets.v1.VBucketSummary.creation_date:type_name -> google.protobuf.Timestamp
	9,  // 5: vbuckets.v1.ListVBucketsResponse.buckets:type_name -> vbuckets.v1.VBucketSummary
	13, // 6: vbuckets.v1.Delta.credentials:type_name -> vbuckets.v1.CredentialsDelta
	14, // 7: vbuckets.v1.Delta.base_host:type_name -> vbuckets.v1.BaseHostDelta
	15, // 8: vbuckets.v1.Delta.vbucket:type_name -> vbuckets.v1.VBucketDelta
	16, // 9: vbuckets.v1.CredentialsDelta.ttl:type_name -> google.protobuf.Duration
	16, // 10: vbuckets.v1.BaseHostDelta.ttl:type_name -> google.protobuf.Duration
	16, // 11: vbuckets.v1.VBucketDelta.ttl:type_name -> google.protobuf.Duration
	0,  // 12: vbuckets.v1.ControlPlane.LookupCredentials:input_type -> vbuckets.v1.LookupCredentialsRequest
	2,  // 13: vbuckets.v1.ControlPlane.LookupBaseHost:input_type -> vbuckets.v1.LookupBaseHostRequest
	4,  // 14: vbuckets.v1.ControlPlane.LookupVBucket:input_type -> vbuckets.v1.LookupVBucketRequest
	6,  // 15: vbuckets.v1.ControlPlane.CreateVBucket:input_type -> vbuckets.v1.CreateVBucketRequest
	8,  // 16: vbuckets.v1.ControlPlane.ListVBuckets:input_type -> vbuckets.v1.ListVBucketsRequest
	11, // 17: vbuckets.v1.ControlPlane.ListenForDeltas:input_type -> vbuckets.v1.ListenForDeltasRequest
	1,  // 18: vbuckets.v1.ControlPlane.LookupCredentials:output_type -> vbuckets.v1.LookupCredentialsResponse
	3,  // 19: vbuckets.v1.ControlPlane.LookupBaseHost:output_type -> vbuckets.v1.LookupBaseHostResponse
	5,  // 20: vbuckets.v1.ControlPlane.LookupVBucket:output_type -> vbuckets.v1.LookupVBucketResponse
	7,  // 21: vbuckets.v1.ControlPlane.CreateVBucket:output_type -> vbuckets.v1.CreateVBucketResponse
	10, // 22: vbuckets.v1.ControlPlane.ListVBuckets:output_type -> vbuckets.v1.ListVBucketsResponse
	12, // 23: vbuckets.v1.ControlPlane.ListenForDeltas:output_type -> vbuckets.v1.Delta
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_controlplane_proto_init() }
func file_v1_controlplane_proto_init() {
	if File_v1_controlplane_proto != nil {
		return
	}
	file_v1_controlplane_proto_msgTypes[12].OneofWrappers = []any{
		(*Delta_Credentials)(nil),
		(*Delta_BaseHost)(nil),
		(*Delta_Vbucket)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_controlplane_proto_rawDesc), len(file_v1_controlplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_controlplane_proto_goTypes,
		DependencyIndexes: file_v1_controlplane_proto_depIdxs,
		MessageInfos:      file_v1_controlplane_proto_msgTypes,
	}.Build()
	File_v1_controlplane_proto = out.File
	file_v1_controlplane_proto_goTypes = nil
	file_v1_controlplane_proto_depIdxs = nil
}
